_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
